### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by jmsv** [yanorestes/rockstar-py#1]
Great work on the transpiler! :smile: 

This issue relates to the part of the README that says:

> I'll work on the readibility and __organization of the code__, would love suggestions on how/where to do that.

Would `rockstar-py` be better structured as a package? E.g.:

- Move `rockstar.py` to `rockstar/__init__.py`
- Add a `setup.py` (setuptools) file, with console script entry point
- Add `rockstar/__main__.py` for running as a module (e.g. `python -m rockstar`)

If you think this is a good idea, I'd be happy to make these changes and open a PR

---

I'm not sure if this is related to this repo not being structured as a package, but after `pip install`ing `rockstar-py` and running `rockstar-py`, a `ModuleNotFoundError` is raised:

```
$ rockstar-py                   
Traceback (most recent call last):
  File "/home/james/.local/share/virtualenvs/test-wygyIHa6/bin/rockstar-py", line 7, in <module>
    from rockstarpy.command_line import main
  File "/home/james/.local/share/virtualenvs/test-wygyIHa6/lib/python3.6/site-packages/rockstarpy/__init__.py", line 1, in <module>
    from .rockstarpy import rockstar
ModuleNotFoundError: No module named 'rockstarpy.rockstarpy'
```

**Comment by yanorestes** [comment]
jmsv, thanks for the issue! The package wasn't properly organized, that should be fixed now. (You will need to clear pip cache and reinstall the package. I could only work it out on another machine :/ but it's working now haha)

**Comment by yanorestes** [comment]
installing with pip lets you use the program in the command line. I'll add this in the README tomorrow morning

**Comment by jmsv** [comment]
Works well now, thanks :+1:
