### ISSUE TITLE
Accepting Invalid Variable Names

### ISSUE THREAD

**Issue by cwfitzgerald** [yanorestes/rockstar-py#13]
As you're currently the primary implementation of rockstar (good job!), I've noticed that the programs that are verified with rockstar-py often contain invalid variable names. For example:

```
Put "value" into value
```

shouldn't compile because "value" isn't a valid variable name (doesn't begin with 'a', 'an', etc. or a capital letter). If you change it to "value" it works fine:

[Before](https://rockstar.connorwfitzgerald.com/?src=UHV0ICJ2YWx1ZSIgaW50byB2YWx1ZQ%3D%3D)
[After](https://rockstar.connorwfitzgerald.com/?src=UHV0ICJ2YWx1ZSIgaW50byBWYWx1ZQ%3D%3D)

I also understand that if you want to accept invalid rockstar (something compilers do often) if you can make heads or tails of it that's perfectly fine too (I do it with variable name spacing), just wanted to make you aware of it.

**Comment by yanorestes** [comment]
Hey, thanks for the issue! Fixed that and ended up fixing some other small regex problems.

I like the compliment <3, but I think rockstar-js is the primary implementation, hehe. Thank you anyway!
