### ISSUE TITLE
Multi line Comments

### ISSUE THREAD

**Issue by iirftw** [yanorestes/rockstar-py#19]
due to the  parenthetic nature of comments in rockstar comments can run across multiple lines such as

	(
	multi
	line
	comment
	)

this can be fixed by replacing " (  " and " ) " with " """ "

**Comment by yanorestes** [comment]
There's no clear specification about multi-line comments in Rockstar. Besides, using `"""` only works on lines with nothing else. This line is invalid, for example:
```python
print('Hello, world!') """this is a comment"""
```
whilst this is valid:
```python
print('Hello, world!') #this is a comment
```
I'll leave the code as it is, regarding comments, at least until multi-line comments are explicitly accepted on Rockstar docs (then I'll think on another solution).
