### ISSUE TITLE
Aint doesn't work

### ISSUE THREAD

**Issue by BenjMonast** [yanorestes/rockstar-py#23]
This code should compile:

    Listen to your heart

    If your heart aint "rock"
    Say "Pick rock, paper, or scissors"

But instead, I get this error: 

    File "output.py", line 2
        if your_heart aint "rock":
                        ^
    SyntaxError: invalid syntax

How come aint doesn't work?

**Comment by yanorestes** [comment]
You're right. I'll work on it rn
