### ISSUE TITLE
While Loops and If Statements

### ISSUE THREAD

**Issue by herbertstrasse** [yanorestes/rockstar-py#25]
When compiled, while statements don't seem to terminate properly. Everything below the looped code just compiles inside the first while statement. Likewise with If statements; a subsequent If statement gets nested inside the first one. I tried leaving blank lines but all that seems to do is add blank lines to the compiled program.

Is this a bug or am I just doing something wrong?

**Comment by yanorestes** [comment]
It's probably a bug caused by the last modification someone made on the indent variable. Can you post your Rockstar code here so I can test it?

**Comment by herbertstrasse** [comment]
Tragedy takes Hope and Fear
While Hope is as great as Fear,
Put Hope without Fear into Hope

(The woman says "Please enter a number...")
(Listen to Hope)
Hope is abandoning
Fear is aberrational
If Tragedy taking Hope, Fear is nothing,
Shout "Even!"
If Tragedy taking Hope, Fear ain't nothing,
Scream "Odd!"

**Comment by herbertstrasse** [comment]
It's a pretty simple even/odd calculator. The input parts are commented out because I can't figure out a way to change the type on inputs (don't think there is a way in rockstar), so I'm just testing it with a static value for now.

**Comment by yanorestes** [comment]
Have you tested with the right blank lines? There should be another blank line after `Put Hope without Fear into Hope`, and a blank line after `Shout "Even!"`

**Comment by yanorestes** [comment]
About the type conversion, I'll work on that! Not sure if Dylan accepted the pr that specified this, but it's basically already defined by the community

**Comment by herbertstrasse** [comment]
Whoops, yeah that was an earlier draft and I missed it. It should be reflected in the edit now. My bad.

**Comment by yanorestes** [comment]
Still missing a blank line after the function, but maybe it's githubs fault. I just tested and the identation works perfectly (adjust the blank lines and it will). The problem is `nothing` is being transpiled to `nothing` instead of 0, I'll check why

**Comment by yanorestes** [comment]
Oh, I see, you should remove the commas (`,`) at the end of your lines. Doing this will fix it. As of rn I'm not sure if it should work with the commas at the end, but this is easy to fix ;). Just don't use them while I don't hahahah

**Comment by herbertstrasse** [comment]
Cool, thank you! I'll try that now.

**Comment by herbertstrasse** [comment]
With this as my .rock file:

Tragedy takes Hope and Fear
While Hope is as great as Fear
Put Hope without Fear into Hope

Give back Hope


(The woman says "Please enter a number...")
(Listen to Hope)
Hope is abandoning
Fear is aberrational
If Tragedy taking Hope Fear is nothing
Shout "Even!"

If Tragedy taking Hope Fear ain't nothing
Scream "Odd!"

I get this output still:

def Tragedy(Hope, Fear):
    while Hope >= Fear:
        Hope = Hope - Fear
        
        return Hope
        
        
         #The woman says "Please enter a number...")
         #Listen to Hope)
        Hope = 0
        Fear = 2
        if Tragedy(hope_fear) == False:
            print("Even!")
            
            if Tragedy(hope_fear) != False:
                print("Odd!")

**Comment by herbertstrasse** [comment]
I'm dumb. It was the line breaks from using a Windows text editor and compiling in unix. Just tried compiling it again and it works perfectly. Sorry!

**Comment by yanorestes** [comment]
Hahahah it's okay! I'll think about implementing something to avoid that. Thanks anyway for coming here and for using rockstar-py!
