### ISSUE TITLE
Arithmetic expressions not working

### ISSUE THREAD

**Issue by martinpetrovaj** [yanorestes/rockstar-py#26]
For example
```
Tango takes Man and Woman
the music is a strife
My Life is Man with the music
My Life is My Life without Woman
Give back My Life
```

is evaluated to 
```
def Tango(Man, Woman):
    the_music = 16
    My_Life = 3435
    My_Life = 2455
    return My_Life
```

Is this a bug or is it in accordance to Rockstar specs?

Also, comparison doesn't seem to be working fully as intended. I got `If Your Heart is nothing,` to transpile into `if Your_Heart = 7:`. It seems that in this case, the transpiler was confused by the comma, as `If Your Heart is nothing` transpiles correctly.
However, comparing two variables (eg. `If Your Heart is Dying` still doesn't work and transpiles as an assignment). For some reason, this works only if I use `your heart` instead of `Your Heart` (where this variable is an output of a function).

**Comment by yanorestes** [comment]
I'll investigate. Thanks for pointing that out, I'll soon have answers
