### ISSUE TITLE
Call to convert_code in main

### ISSUE THREAD

**Issue by Vaarai** [yanorestes/rockstar-py#4]
Line 175, your call to convert_code is preceded by 'rockstar.', so it doesn't work.

origin:
rockstar.convert_code(rockstar_code, py_rockstar)

fix:
convert_code(rockstar_code, py_rockstar)

It's working !!

**Comment by yanorestes** [comment]
It works. The problem was the missin `import re`, but it's now fixed on version 1.1.2
