### ISSUE TITLE
function calls do not get transpiled if there is anything else on the line

### ISSUE THREAD

**Issue by kennethgoodman** [yanorestes/rockstar-py#6]
`r'([A-Za-z]+(?: [A-Za-z]+)*) taking ([A-Za-z0-9_]+(?:, [A-Za-z_0-9]+)*)'`

will match:

`Multiply taking 3, 4`

but not:

`Say Multiply taking 3, 4` or anything else where a function call is mid-line.

Side point:

`Multiply taking 3,4` doesn't either work

**Comment by yanorestes** [comment]
What? `Say Multiply taking 3, 4` works fine and even the fizzbuzz example uses function calls midline. I don't get the issue. What error are you getting? Will fix parameters division without space in a sec

**Comment by yanorestes** [comment]
`re.sub()` is different from `re.match()`, so it matches even if the match is not at the beginning of the line
